### PR TITLE
Replace `call_external`'s implementation with an async one

### LINKED ISSUE #1759: Opening a URL or avatar freezes Profanity for as long as the opened executable is currently running
## Expected Behavior

Being able to use profanity while the opened executable is running

## Current Behavior

Profanity freezes until I kill the opened executable

## Possible Solution

Replace `g_spawn_sync` with `g_spawn_async` in `call_external`

## Steps to Reproduce (for bugs)

1. Have `/url open` set to open a browser, for example like Firefox or Chromium
2. Close any existing browsers
3. Open a URL in profanity using `/url open`

## Context

This is noticable, if for example, `/url open` opens a new browser

## Environment
* Artix Linux (OpenRC)
* glib:  2.72.3
```
Profanity, version 0.13.0dev.feature/1158-vcard.2e84acce
Copyright (C) 2012 - 2019 James Booth <boothj5web@gmail.com>.
Copyright (C) 2019 - 2022 Michael Vetter <jubalh@iodoru.org>.
License GPLv3+: GNU GPL version 3 or later <https://www.gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Build information:
XMPP library: libstrophe
Desktop notification support: Enabled
OTR support: Enabled (libotr 4.1.1)
PGP support: Enabled (libgpgme 1.18.0)
OMEMO support: Enabled
C plugins: Enabled
Python plugins: Enabled (3.10.7)
GTK icons/clipboard: Enabled
GDK Pixbuf: Enabled
```

### PR DESCRIPTION
**Pull request by techmetx11**
The original `call_external` is kept as `call_external_sync`

Fixes #1759

### CODE REVIEW

**Comment by jubalh** [comment]
I don't quite see where `call_external_sync()` is used/needed now?

**Comment by techmetx11** [comment]
Me neither, I left it there for compatibility, but maybe it'll be better if I remove it

**Comment by jubalh** [comment]
We are no library :)
So don't need to worry about compatibility in the regard of not renaming/removing functions.

I'll have to check the code later. Did you test if all the situations that use this function now still work?

**Comment by techmetx11** [comment]
> We are no library :) So don't need to worry about compatibility in the regard of not renaming/removing functions.
> 
> I'll have to check the code later. Did you test if all the situations that use this function now still work?

I've only tested it with `/url open` right now

**Review by jubalh — CHANGES_REQUESTED** [review]
If all the functions that use `call_external` work you can actually remove `call_external_sync`, no need to keep it.

**Comment by techmetx11** [comment]
> If all the functions that use `call_external` work you can actually remove `call_external_sync`, no need to keep it.

I removed it now :3

**Comment by jubalh** [comment]
Did you also test the functionality which calls this function?

And since it's now two commits about one change you can squash it into one.

**Comment by techmetx11** [comment]
> Did you also test the functionality which calls this function?
> 
> And since it's now two commits about one change you can squash it into one.

I've tried it out with `/avatar open`, `/url open` (both HTTP and AESGCM) and `/url save`
I'll squash it

File: src/common.c [hunk 1]
```diff
@@ -443,44 +443,24 @@ get_mentions(gboolean whole_word, gboolean case_sensitive, const char* const mes
...
     if (!is_successful) {
         gchar* cmd = g_strjoinv(" ", argv);
-        log_error("Spawning '%s' failed with with error '%s'", cmd, spawn_error ? spawn_error->message : "Unknown, spawn_error is NULL");
-        ;
+        log_error("Spawning '%s' failed with error '%s'", cmd, spawn_error ? spawn_error->message : "Unknown, spawn_error is NULL");
 
         g_error_free(spawn_error);
         g_free(cmd);
-    } else {
-        is_successful = g_spawn_check_exit_status(wait_status, &exit_error);
```
[the remark this answers is not in the document]
Comment (techmetx11) [reply src/common.c:475]: You could setup some child watch with the child PID

File: src/common.c [hunk 2]
```diff
@@ -443,44 +443,35 @@ get_mentions(gboolean whole_word, gboolean case_sensitive, const char* const mes
 }
 
 gboolean
-call_external(gchar** argv, gchar** std_out, gchar** std_err)
+call_external(gchar** argv, gint* std_out, gint* std_in, gint* std_error, GPid* pid)
```
Comment (sjaeckel) [inline src/common.c:446]: What's the point of adding those two parameters and then not using them?

IMO the better change here would be to remove those two parameters that are unused.

File: src/common.c (hunk 1 above)
[the remark this answers is not in the document]
Comment (sjaeckel) [reply src/common.c:475]: Do we really care what happened after the process was spawned? I think it can stay like this.

**Review by sjaeckel — CHANGES_REQUESTED** [review]
Looks acceptable to me.

Please also squash the commits into one.

**Review by jubalh — CHANGES_REQUESTED** [review]
Please see @sjaeckel s comments.
After this we can merge :)

File: src/common.c (hunk 2 above)
Comment (techmetx11) [reply src/common.c:446]: Should I be removing the 4 parameters in the new `call_external`?

Comment (jubalh) [reply src/common.c:446]: Yes, it looks like they are not used anywhere.

Comment (techmetx11) [reply src/common.c:446]: Sure :3

File: src/common.c [hunk 3]
```diff
@@ -443,44 +443,26 @@ get_mentions(gboolean whole_word, gboolean case_sensitive, const char* const mes
...
-                                 argv,
-                                 NULL, // Inherit the parent environment.
-                                 flags,
-                                 NULL, NULL, // No func. before exec() in child.
-                                 std_out, std_err,
-                                 &wait_status, &spawn_error);
 
+    GSpawnFlags flags = G_SPAWN_SEARCH_PATH | G_SPAWN_STDOUT_TO_DEV_NULL | G_SPAWN_STDERR_TO_DEV_NULL;
+
+    is_successful = g_spawn_async_with_pipes(NULL, // Inherit the parent PWD
```
Comment (jubalh) [inline src/common.c:453]: Why `g_spawn_async_with_pipes()` and not `g_spawn_async()` ?

Comment (sjaeckel) [reply src/common.c:453]: Because before there were all those arguments, but now they're not used anymore, so the slimmer API `g_spawn_async()` could be used ... which under the hood still calls `g_spawn_async_with_pipes()` https://docs.gtk.org/glib/func.spawn_async.html ... :D

Comment (jubalh) [reply src/common.c]: i'll change it.

**Review by jubalh — APPROVED** [review]

**Comment by jubalh** [comment]
Thanks for your contribution @techmetx11 !
