### PR TITLE
Cast chat/muc window to correct type and refactor cmd_sendfile

### LINKED ISSUE #1449: Sendfile command encrypts files for regular MUC
@mdosch discovered that the sendfile command encrypts files for regular MUC.

## Expected Behavior
/sendfile should send a `https://...` URL in regular MUCs

## Current Behavior
/sendfile encrypts the file using AES GCM (`aesgcm://` URL) due to #1262 

## Possible Solution
Fix the `switch` in `cmd_funcs.c`.

## Steps to Reproduce (for bugs)

1. Enter a regular MUC
2. Do `/sendfile image.jpeg`
3. Voila!

## Context
N/A

## Environment
N/A

### PR DESCRIPTION
**Pull request by wstrm**
Fixes #1449

### CODE REVIEW

File: src/command/cmd_funcs.c [hunk 1]
```diff
@@ -4889,43 +4889,52 @@ cmd_sendfile(ProfWin* window, const char* const command, gchar** args)
...
 
+    gboolean omemo_enabled = FALSE;
+    gboolean sendfile_enabled = TRUE;
+
     switch (window->type) {
     case WIN_MUC:
+    {
+        ProfMucWin* mucwin = (ProfMucWin*)window;
+        assert(mucwin->memcheck == PROFMUCWIN_MEMCHECK);
+        omemo_enabled = mucwin->is_omemo == TRUE;
```
Comment (jubalh) [inline src/command/cmd_funcs.c:4900]: What's the difference between this and `omemo_enabled = mucwin->is_omemo` ?

File: src/common.c [hunk 2]
```diff
@@ -629,15 +629,15 @@ _basename_from_url(const char* url)
...
     GString* exp_path = g_string_new("");
-    gchar *result;
+    gchar* result;
 
     if (strlen(path) >= 2 && path[0] == '~' && path[1] == '/') {
-        g_string_printf(exp_path, "%s/%s", getenv("HOME"), path+2);
+        g_string_printf(exp_path, "%s/%s", getenv("HOME"), path + 2);
     } else {
-        g_string_printf(exp_path, "%s", path+2);
+        g_string_printf(exp_path, "%s", path);
```
Comment (jubalh) [inline src/common.c:640]: Damn.. Sorry for copy/paste mistake :(

File: src/common.c [hunk 3]
```diff
@@ -649,11 +649,11 @@ get_expanded_path(const char *path)
 gchar*
 unique_filename_from_url(const char* url, const char* path)
 {
-    gchar *realpath;
+    gchar* realpath;
 
     // Default to './' as path when none has been provided.
     if (path == NULL) {
-        realpath = strdup("./");
+        realpath = g_strdup("./");
```
Comment (jubalh) [inline src/common.c:656]: Ouch!
