### PR TITLE
Fix OMEMO devicelist access model by reconfiguring it

### LINKED ISSUE #1538: [OMEMO] profanity should fix the PEP access model if wrongly configured by another client
Me and my friend use the same version of profanity, we both have two OMEMO keys, one from another client and one created in profanity. When we do `/omemo fingerprint <account>` we only get the fingerprint of another client, but the profanity of the other is not listed. 

But if we both do: `/omemo fingerprint` in the console, if the hash of profanity and that of the other client we use come out

I followed the steps detailed here: https://github.com/profanity-im/blog/blob/master/content/post/omemo.md , but it only lists one of the IDs of your mobile device but not that of your profanity client.

When we want to use Omemo and he writes to me from his profanity client I get this message: "You received a message encrypted with OMEMO but your client doesn't support OMEMO." `¯\_(ツ)_/¯`

```
$ uname -a
OpenBSD 6.9 GENERIC#464 amd64

$ profanity --version
Profanity, version 0.10.0
Copyright (C) 2012 - 2019 James Booth <boothj5web@gmail.com>.
Copyright (C) 2019 - 2021 Michael Vetter <jubalh@iodoru.org>.
License GPLv3+: GNU GPL version 3 or later <https://www.gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Build information:
XMPP library: libmesode
Desktop notification support: Disabled
OTR support: Enabled (libotr 4.1.1)
PGP support: Enabled (libgpgme 1.15.1)
OMEMO support: Enabled
C plugins: Enabled
Python plugins: Enabled (3.8.8)
GTK icons: Disabled
```

### PR DESCRIPTION
**Pull request by paulfariello**
Fix #1538

Handle precondition-not-met returned when inserting our device in the device list. Try to reconfigure it properly and give up if it fails again.

Also add support for missing device list node. It rely on auto-create. We should ensure this feature is enabled and fallback to a proper create with config otherwise.

### CODE REVIEW

File: src/omemo/omemo.c [hunk 1]
```diff
@@ -386,6 +386,7 @@ omemo_publish_crypto_materials(void)
 
     char* barejid = connection_get_barejid();
 
+
```
Comment (jubalh) [inline src/omemo/omemo.c:389]: ? :)

File: src/xmpp/omemo.c [hunk 2]
```diff
@@ -507,11 +542,105 @@ _omemo_receive_devicelist(xmpp_stanza_t* const stanza, void* const userdata)
...
+
+        xmpp_stanza_t *error = xmpp_stanza_get_child_by_name(stanza, "error");
+        if (!error) {
+            log_error("[OMEMO] Missing error element in device list publication result");
+            return 0;
+        }
+
+        xmpp_stanza_t *pubsub_error = xmpp_stanza_get_child_by_ns(error, STANZA_NS_PUBSUB_ERROR);
+        if (!pubsub_error) {
+            // TODO
```
Comment (jubalh) [inline src/xmpp/omemo.c:566]: todo what?

**Review by jubalh — CHANGES_REQUESTED** [review]

**Comment by jubalh** [comment]
Awesome! Thanks for this!

File: src/xmpp/omemo.c [hunk 3]
```diff
@@ -507,11 +542,105 @@ _omemo_receive_devicelist(xmpp_stanza_t* const stanza, void* const userdata)
...
+            return 0;
+        }
+
+        if (g_strcmp0(xmpp_stanza_get_name(pubsub_error), "precondition-not-met") == 0) {
+            static gboolean reconfigured = false;
```
Comment (jubalh) [inline src/xmpp/omemo.c:571]: I'm unsure whether this works as intended.

File: src/xmpp/omemo.c [hunk 4]
```diff
@@ -507,11 +542,105 @@ _omemo_receive_devicelist(xmpp_stanza_t* const stanza, void* const userdata)
...
+
+    if (g_strcmp0(type, STANZA_TYPE_ERROR) == 0) {
+        log_error("[OMEMO] cannot configure device list to an open access model: Result error");
+        return 0;
+    }
+
+    log_debug("[OMEMO] node configured");
+
+    // Try to publish
+    char* barejid = connection_get_barejid();
```
Comment (jubalh) [inline src/xmpp/omemo.c:638]: barejid needs to be freed. memleak.

File: src/xmpp/omemo.c (hunk 3 above)
Comment (jubalh) [reply src/xmpp/omemo.c:571]: we will after the first run always be in `true` but it could be that we switch accounts without restarting profanity. or it could be that we need to republish because while profanity was running another client did something to the devicelist and we need to republish.

**Comment by jubalh** [comment]
> It rely on auto-create. We should ensure this feature is enabled and fallback to a proper create with config otherwise.

I asked around and heard that the auto-create is pretty common. So we probably don't have to bother with adding the fallback.

**Review by jubalh — APPROVED** [review]

**Comment by jubalh** [comment]
There is the corner case with the static variable mentioned in the review above.

Instead of using a static variable we maybe could also pass it along the userdata parameter. That's a long line of calls. According to paul:
* _omemo_devicelist_publish_result
*  omemo_devicelist_configure
*  _omemo_devicelist_configure_submit
*  _omemo_devicelist_configure_result 
* omemo_devicelist_request
*  _omemo_receive_devicelist
*  omemo_set_device_list 
* _handle_own_device_list 
*  omemo_devicelist_publish 
*  _omemo_devicelist_publish_result

omemo_devicelist_request and _handle_own_device_list seem to be not so easy.

The corner cases probably will be quite rare anyways.

**Comment by paulfariello** [comment]
The issue with the static boolean could arise in two cases:
  - deconnection from a client that already reconfigured it's own device list. Followed by a connection to another account that also have a misconfigured device list.
  - running client that has already reconfigured it's own device list. With another client misconfiguring the existing devicelist and removing the running client from the list.
Each time the effect would be that profanity won't be able to reconfigure correctly the devicelist.
